# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import clone_tts_pb2 as clone__tts__pb2


class CloneTTSServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Synthesize = channel.unary_unary(
        '/clone_tts.CloneTTSService/Synthesize',
        request_serializer=clone__tts__pb2.CloneInput.SerializeToString,
        response_deserializer=clone__tts__pb2.CloneResponse.FromString,
        )


class CloneTTSServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Synthesize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CloneTTSServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Synthesize': grpc.unary_unary_rpc_method_handler(
          servicer.Synthesize,
          request_deserializer=clone__tts__pb2.CloneInput.FromString,
          response_serializer=clone__tts__pb2.CloneResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'clone_tts.CloneTTSService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
